FROM n8nio/n8n:latest

# Install curl and ffmpeg on Alpine
USER root
RUN apk add --no-cache curl ffmpeg

# Enable community nodes and external modules
ENV N8N_ENABLE_LOAD_EXTERNAL_MODULES=true
ENV N8N_COMMUNITY_NODES_AUTO_INSTALL=true
ENV NODE_FUNCTION_ALLOW_EXTERNAL=axios,crypto,moment

# Revert back to node user
USER node

# Rest of your ARGs and ENVs...
ARG PGPASSWORD
ARG PGHOST
ARG PGPORT
ARG PGDATABASE
ARG PGUSER

ARG USERNAME
ARG PASSWORD

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=$PGDATABASE
ENV DB_POSTGRESDB_HOST=$PGHOST
ENV DB_POSTGRESDB_PORT=$PGPORT
ENV DB_POSTGRESDB_USER=$PGUSER
ENV DB_POSTGRESDB_PASSWORD=$PGPASSWORD

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=$USERNAME
ENV N8N_BASIC_AUTH_PASSWORD=$PASSWORD

ENV ENABLE_ALPINE_PRIVATE_NETWORKING=true

CMD ["n8n", "start"]
